fat:./fat.asm ./fat32fsinfo.asm ./rootdir.asm
	nasm ./fat32fsinfo.asm -o ../../build/fat32fsinfo.bin
	nasm ./fat.asm -o ../../build/fat.bin
	nasm ./rootdir.asm -o ../../build/rootdir.bin
sym:./symtable.asm
	nasm ./symtable.asm -o ../../build/symbol.bin
